### ISSUE TITLE
Pre-compilation (WARNING: Method definition) warnings after adding MLJ macro interface to package

### ISSUE THREAD

**Issue by PyDataBlog** [JuliaAI/MLJModelInterface.jl#34] opened 2020-04-10 08:32 UTC
**Describe the bug**

After adding the recommended interface Julia file using the macro (https://alan-turing-institute.github.io/MLJ.jl/dev/quick_start_guide_to_adding_models/#Model-type-and-constructor-1) which is needed to connect the package to the specified MLJ models interface, a pre-compilation warning now has shown up. 

**To Reproduce**

To recreate simply clone the experimental branch of the project that contains the MLJ interface
```julia
pkg> dev git@github.com:PyDataBlog/ParallelKMeans.jl.git
```

Don't forget to switch to the experimental branch and test the newly add package in shell mode:

```julia
shell> git checkout experimental
```
Test the package to reproduce the warnings now:

```julia
pkg> test ParallelKMeans
```

An example of the warning on TravisCI: https://travis-ci.org/github/PyDataBlog/ParallelKMeans.jl/jobs/673173247#L284-L289
```
WARNING: Method definition (::Type{ParallelKMeans.KMeans})() in module ParallelKMeans overwritten.
  ** incremental compilation may be fatally broken for this module **

WARNING: Method definition Type(Any, Type{ParallelKMeans.KMeans}) in module ParallelKMeans overwritten.
  ** incremental compilation may be fatally broken for this module **
```

**Expected behavior**
A successful compilation of the package without the 2 warnings. The warnings seem to disappear after the first compilation is done. Subsequent testing of the package won't show the warning. It only appears after changes are made to the code which requires another pre-compilation. 

**Versions**
MLJModelInterface v0.2.1
MLJBase v0.12.6

**Comment by tlienart** [comment] 2020-04-10 08:42
Hello,

I've encountered this issue before. We need to dig a bit into why exactly it happens and how to fix it cleanly but in the mean time you can do one of the following:

1. "easy" one, don't use `@mlj_model` for now, use for instance Parameters like in https://github.com/alan-turing-institute/MLJLinearModels.jl/blob/master/src/mlj/classifiers.jl and add a `clean!` method to test that arguments given have the necessary constraints (https://github.com/alan-turing-institute/MLJModels.jl/blob/9e4ef60c6405c10a4d8659c04f524173be610fda/src/ScikitLearn/svm.jl#L62) 
1. "module"  one, follow https://github.com/alan-turing-institute/MLJModelInterface.jl/issues/20#issue-567056184 

I would suggest going with the first one for now as it's the quickest one and I'm pretty sure it will solve your problem.

**Note**: we do want to make this `@mlj_model` macro work for everyone, but it turns out it's pretty hard to know exactly in what environment the macro should be evaluated when you have a string of packages depending upon one another. Note also that the issue, while inelegant, seems innocuous (no impaired functionalities) but of course it's still ugly.

**Comment by PyDataBlog** [comment] 2020-04-10 09:29
@tlienart  We will go with the first option then. Hopefully, this issue is fixed later for the convenience of the macro style. Maybe the docs can include a warning about the experimental nature of the macro declarations?

**Comment by tlienart** [comment] 2020-04-10 09:35
Thanks, the thing is that we already use `@mlj_model` macro extensively within MLJModel itself so we know it works and is robust; the issue is caused bc of *when* the stuff is evaluated which makes the compiler not happy (but effectively what is supposed to happen, happens).

Anyway in the issue I linked to the idea was to basically drop suggesting `@mlj_model` for now for external packages (so that people wouldn't see the issue you're seeing).  On the other hand, on our roadmap we intend to fragment MLJModels so that we don't have to actively load external packages like MultivariateStats etc and so that will force us to look into this `@mlj_model` in more details & hopefully fix it or remove it. (macros are great but become nightmarish as soon as you have chains of imports and evaluations). 

I'll close this issue now but feel free to reopen if you have an issue, also  feel free to ping me directly from ParallelKMeans if you'd like me to review your interface.

**Closed as completed** 2020-04-10 09:36 UTC

**Comment by OkonSamuel** [comment] 2020-07-26 21:59
The issue with `@mlj_model` macro has been solved in the latest release.

**Comment by tlienart** [comment] 2020-07-27 06:22
Wonderful!! Thanks sam!
